#!/usr/bin/env python3
"""Auto-update README with GitHub activity and projects."""

import os
from datetime import datetime
from github import Github

TOKEN = os.getenv('GITHUB_TOKEN')
g = Github(TOKEN)
user = g.get_user()

def get_recent_projects(limit=5):
    """Get user's recent repositories."""
    repos = sorted(
        [r for r in user.get_repos() if not r.fork],
        key=lambda x: x.pushed_at,
        reverse=True
    )[:limit]
    
    md = ""
    for repo in repos:
        desc = repo.description or "*No description*"
        md += f"- [{repo.name}]({repo.html_url}) - {desc}\n"
    return md

def get_recent_activity(limit=5):
    """Get user's recent events."""
    events = user.get_events()[:limit * 3]
    
    activity = []
    for event in events:
        if event.type == "PushEvent":
            repo = event.repo.name
            commits = event.payload.get('size', 0)
            if commits > 0:
                activity.append(f"- Pushed {commits} commit(s) to [{repo}]({event.repo.html_url})")
        elif event.type == "PullRequestEvent":
            action = event.payload.get('action')
            pr_num = event.payload['number']
            repo = event.repo.name
            if action == 'opened':
                activity.append(f"- Opened PR #{pr_num} on [{repo}]({event.repo.html_url})")
        elif event.type == "CreateEvent":
            ref_type = event.payload.get('ref_type')
            if ref_type == 'repository':
                activity.append(f"- Created [{event.repo.name}]({event.repo.html_url})")
    
    return "\n".join(activity[:limit]) if activity else "*No recent activity*"

def update_readme():
    """Update README.md."""
    with open('README.md', 'r', encoding='utf-8') as f:
        content = f.read()
    
    projects = get_recent_projects(5)
    content = content.replace(
        '<!--START_SECTION:projects-->\n*This section updates automatically via GitHub Actions*\n<!--END_SECTION:projects-->',
        f'<!--START_SECTION:projects-->\n{projects}<!--END_SECTION:projects-->'
    )
    
    content = content.replace(
        '<!--START_SECTION:latest-->\n*This section updates automatically via GitHub Actions*\n<!--END_SECTION:latest-->',
        f'<!--START_SECTION:latest-->\n{projects}<!--END_SECTION:latest-->'
    )
    
    activity = get_recent_activity(5)
    content = content.replace(
        '<!--START_SECTION:activity-->\n*This section updates automatically via GitHub Actions*\n<!--END_SECTION:activity-->',
        f'<!--START_SECTION:activity-->\n{activity}\n<!--END_SECTION:activity-->'
    )
    
    now = datetime.now().strftime('%Y-%m-%d %H:%M UTC')
    content = content.replace(
        '<!--UPDATE_TIME-->Auto-generated by GitHub Actions<!--UPDATE_TIME-->',
        f'<!--UPDATE_TIME-->{now}<!--UPDATE_TIME-->'
    )
    
    with open('README.md', 'w', encoding='utf-8') as f:
        f.write(content)

if __name__ == '__main__':
    update_readme()
